# Generated by Django 5.2.4 on 2026-06-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_orders_per_month',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
