# Generated by Django 5.2.4 on 2026-06-11 05:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_subscriptionplan_unlimited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='sms_api_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
