# Generated by Django 5.2.4 on 2026-06-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
