# Generated by Django 5.2.4 on 2026-06-11 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_payment_status'),
        ('merchants', '0002_subscriptionplan_unlimited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedtransactioncache',
            name='source',
            field=models.CharField(default='sms', max_length=20),
        ),
        migrations.AlterField(
            model_name='verifiedtransactioncache',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
    ]
